development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: testexample_development
  pool: 5
  username: root
  password: qwerty
  socket: /var/run/mysqld/mysqld.sock

 ioioioioioioio